version: '3.7'

services:
  web_api:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    container_name: api

  redis:
    image: redis:8.0
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - ./redis_data:/var/lib/redis
    container_name: redis